from src.entrega2.tipos.Lista_ordenada_sin_repeticion import *

lista_ord = Lista_ordenada_sin_repeticion()
lista_ord.of(lambda x:-x)
lista_ord.add(23)
lista_ord.add_all([47,47,1,2,-3,4,5])
lista_ord.print_list()
print("\n----------------------------\n")
lista_ord.add(0)
lista_ord.print_list()
print("\n----------------------------\n")
lista_ord.add(0)
lista_ord.print_list()
print("\n----------------------------\n")
lista_ord.add(7)
lista_ord.print_list()
print("\n----------------------------\n")
print(lista_ord.remove())
print("\n----------------------------\n")
print(lista_ord.remove_all())
print("\n----------------------------\n")
lista_ord.add_all([3,65,3,-1,6,76,5,3])
lista_ord.print_list()
print("\n----------------------------\n")
lista_ord.of(lambda x:x) #del revés
lista_ord.print_list()
print("\n----------------------------\n")